### ISSUE TITLE
你好想问下数据集转换不对的问题

### ISSUE THREAD

**Issue by dahu-1998** [onehahaha756/yolov5_rotation#8]
## ❔Question

在DOTA数据集转换的时候报错，说 ValueError: 'ship' is not in list
## Additional context
数据集格式：807 331 800 324 817 309 823 316 ship 0

**Comment by ASguoyue** [comment]
> 

你好请问一下你转化成功了没

**Comment by dahu-1998** [comment]
没呢，转化失败，标签不对，不知道标签定义的是1,2,3，还是A,B,C

**Comment by dahu-1998** [comment]
Traceback (most recent call last):
  File "D:/PycharmProjects/yolov5_rotation-master/utils/cut2rotation.py", line 387, in <module>
    cutimage2detect(args.input_imgdir,args.input_annotdir,args.saveimg_dir,args.saveannot_dir,args.cut_size,args.overlap,args.save_nage_ratio,args.vis_label)
  File "D:/PycharmProjects/yolov5_rotation-master/utils/cut2rotation.py", line 311, in cutimage2detect
    polygon_list=txt2polygons(annotpath)
  File "D:/PycharmProjects/yolov5_rotation-master/utils/cut2rotation.py", line 39, in txt2polygons
    annot_name=row_list[-2]
IndexError: list index out of range

进程已结束，退出代码

使用cut2rotation转化报错

**Comment by dahu-1998** [comment]
> > 
> 
> 你好请问一下你转化成功了没

我对代码做了一点更改，可以正常转化了
