### ISSUE TITLE
训练完成，但测试标签出错

### ISSUE THREAD

**Issue by dahu-1998** [onehahaha756/yolov5_rotation#9]
## ❔Question
我跑自己的数据集，但是在训练的时候却还是检测dota的数据集ship

## Additional context
detected 3 ships!
runs\detect\exp10\vis_results\00001.png saved!
0/57  processing 00001.jpg  shape:(1024, 1280, 3) (0.095s ETA: 5.415s)
detected 2 ships!
runs\detect\exp10\vis_results\000010.png saved!
1/57  processing 000010.jpg  shape:(1024, 1280, 3) (0.100s ETA: 5.602s)
detected 3 ships!

**Comment by onehahaha756** [comment]
代码细节print的时候默认输出的是ship，我还没有修改。有时间的时候，我可能会整理更新一下代码。

**Comment by ASguoyue** [comment]
> 代码细节print的时候默认输出的是ship，我还没有修改。有时间的时候，我可能会整理更新一下代码。

老哥，请问一下我的这个是什么问题呢，可以训练，测试报错
Traceback (most recent call last):
  File "/home/atr2/PycharmProjects/yolov5_rotation-master/test_rotation.py", line 296, in <module>
    test(**vars(opt))
  File "/home/atr2/anaconda3/envs/dete/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/atr2/PycharmProjects/yolov5_rotation-master/test_rotation.py", line 99, in test
    prefix=colorstr(f'{task}: '))[0]
  File "/home/atr2/PycharmProjects/yolov5_rotation-master/utils/datasets.py", line 84, in create_dataloader
    prefix=prefix)
  File "/home/atr2/PycharmProjects/yolov5_rotation-master/utils/datasets.py", line 418, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
